#!/usr/bin/env python3
"""audit_ab21_ab22.py — mechanical adjudication of the AB21/AB22 (OVIS/CAP) inversion.

External claim under test (Tsirkas 2026, "Auditing the Unread", defect D4,
github.com/ChristosTsirkas/corpus-validation-for-undeciphered-scripts-linear-a):
the Douros tabulation behind lineara.xyz — the source our silver corpus is
normalised from (scripts/corpus_io.py) — systematically swaps the livestock
logograms AB21 (*21, OVIS/sheep) and AB22 (*22, CAP/goat) in a specific set of
documents. Younger's own records and the decoded SigLA database agree against it.

This script re-adjudicates from witnesses held in THIS repo only:
  - silver:  corpus/silver/inscriptions.json           (lineara.xyz lineage)
  - SigLA:   corpus/bronze/sigla_browse_2026/sigla_documents.json
             (decoded by scripts/sigla_decode.py; family level only — SigLA
             carries no M/F gender variants)

Younger's prose records (corpus/bronze/younger_lineara/{HTtexts,misctexts}.txt)
were checked by eye for the same documents (OVIS/CAP wordings); they agree with
SigLA at every site checked. They are not machine-parsed here.

Output: one row per silver *21/*22-family token in documents present in SigLA,
with the SigLA family reading and a verdict per document set. Counts in
docs/2026-08-05-ab21-ab22-external-audit.md are generated by this script
(invariant 12).
"""
import json
import re
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FAMILY = {"*21": "21", "*21M": "21", "*21F": "21",
          "*22": "22", "*22M": "22", "*22F": "22"}


def sigla_designation(silver_id: str) -> str:
    """HT136a -> 'HT 136a', KNWc29 -> 'KN Wc 29', PH(?)31a -> 'PH 31a'."""
    m = re.match(r"([A-Z]+)(\(\?\))?(Wc)?(\d+[a-z]?)", silver_id)
    if not m:
        return silver_id
    site, _, wc, num = m.groups()
    return f"{site} Wc {num}" if wc else f"{site} {num}"


def main() -> int:
    silver = json.loads((ROOT / "corpus/silver/inscriptions.json").read_text())
    sigla = json.loads(
        (ROOT / "corpus/bronze/sigla_browse_2026/sigla_documents.json").read_text())
    sigla_by_des = {d["designation"]: d for d in sigla}

    rows = []
    for doc in silver:
        tokens = [s for s in doc["signs"] if s in FAMILY]
        if not tokens:
            continue
        des = sigla_designation(doc["id"])
        sd = sigla_by_des.get(des)
        sig_fams = ([s[-2:] for s in sd["transcription"] if s in ("AB21", "AB22")]
                    if sd else None)
        rows.append((doc["id"], des, tokens, sig_fams))

    n_tok = sum(len(t) for _, _, t, _ in rows)
    print(f"silver documents with *21/*22-family tokens: {len(rows)}  "
          f"(total tokens: {n_tok})")
    print(f"{'silver id':<12} {'SigLA doc':<12} {'silver (family)':<22} "
          f"{'SigLA (family)':<18} verdict")

    verdicts = Counter()
    for sid, des, tokens, sig in rows:
        fams = [FAMILY[t] for t in tokens]
        if sig is None:
            v = "NOT_IN_SIGLA"
        elif len(sig) != len(fams):
            v = "COUNT_MISMATCH"          # alignment not attemptable at family level
        elif all(a == b for a, b in zip(fams, sig)):
            v = "AGREE"
        elif all(a != b for a, b in zip(fams, sig)):
            v = "INVERTED"
        else:
            v = "MIXED"
        verdicts[v] += 1
        print(f"{sid:<12} {des:<12} {','.join(fams):<22} "
              f"{','.join(sig) if sig else '-':<18} {v}")

    print("\nper-document verdicts:", dict(verdicts))
    inverted_tokens = sum(
        len(t) for sid, des, t, sig in rows
        if sig is not None and len(sig) == len(t)
        and all(FAMILY[a] != b for a, b in zip(t, sig)))
    print(f"tokens in fully-INVERTED documents: {inverted_tokens} / {n_tok}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
